version: '3.8'

services:
  app:
    build: .
    expose:
      - "3000"
    environment:
      - NODE_ENV=production
    env_file:
     - .env
    volumes:
      - ./views:/usr/src/app/views
      - ./src:/usr/src/app/src
    restart: unless-stopped
    ports:
      - '8882:3000'